new sidebar with responsive header and sidebar
bushra-rauf/Australia-Zoo-Team-Grade pull request #33
Opened 2024-11-28 21:11 UTC by Souad-Sud

Please review and test so we can merge this to main. There is some changes in header and footer and sdebar so just accept changes

2024-11-28 21:21 UTC, Souad-Sud commented
And please do not add anything eles to the header and the footer its fixed

2024-11-29 08:39 UTC, ranjithavelusamy approved these changes
fine

2024-11-29 09:34 UTC, bushra-rauf requested changes

2024-11-29 09:34 UTC, bushra-rauf commented on scripts/sidebar.js
What is this for. please delete your code. you have already choosen your page to do your js. On Miro board my name is on it.

2024-11-29 09:35 UTC, bushra-rauf commented on scripts/sidebar.js
The animal name coming on page. I am working on it

2024-11-29 09:47 UTC, Moshira89 commented
The animal list needs fixing.

2024-11-29 09:47 UTC, bushra-rauf approved these changes

2024-11-29 09:47 UTC, bushra-rauf commented on scripts/sidebar.js
ok i will change it later. i am approving

2024-11-29 10:30 UTC, merged